#!/bin/bash
# Hook triggered after a squad/agent completes a session to extract instincts

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$DIR")")"
INSTINCTS_DIR="$PROJECT_ROOT/.agent/knowledge/instincts"

LOG_FILE=$1

if [ -z "$LOG_FILE" ] || [ ! -f "$LOG_FILE" ]; then
    echo "No valid log file provided for learning extraction."
    exit 0
fi

echo "🧠 Extracting session learnings from $(basename "$LOG_FILE")..."
mkdir -p "$INSTINCTS_DIR"

# Basic heuristic to find key pattern lines or lessons generated by the LLM (e.g. marked with 'LESSON:' or 'LEARNING:')
LEARNINGS=$(grep -iE "LESSON:|LEARNING:|PATTERN:" "$LOG_FILE" || true)

if [ -z "$LEARNINGS" ]; then
    echo "No explicit learnings found in log."
    exit 0
fi

INSTINCT_ID=$(date +%s)
INSTINCT_FILE="$INSTINCTS_DIR/instinct-$INSTINCT_ID.md"

echo "---" > "$INSTINCT_FILE"
echo "id: $INSTINCT_ID" >> "$INSTINCT_FILE"
echo "source: $(basename "$LOG_FILE")" >> "$INSTINCT_FILE"
echo "confidence: 0.8" >> "$INSTINCT_FILE"
echo "---" >> "$INSTINCT_FILE"
echo "" >> "$INSTINCT_FILE"
echo "# Session Learnings" >> "$INSTINCT_FILE"
echo "$LEARNINGS" >> "$INSTINCT_FILE"

echo "Instinct created: $INSTINCT_FILE"
exit 0
